version: 2
mergeable:
  - when: pull_request.*
    name: "Conventional Commits"
    validate:
      - do: title
        begins_with:
          match: ['feat', 'fix', 'api', 'refactor', 'perf', 'test', 'style', 'chore', 'cargo']

    fail:
      - do: checks
        status: "action_required"
        payload:
          title: PR title should follow conventional commits
          summary: "PR title should follow https://conventionalcommits.org. E.g. start with 'feat:' (for Features / Changes), 'fix:' (for Fixes), 'api:' (for API-Changes), 'api!:' (for breaking API-Changes) 'refactor:' (for Refactor), 'perf:' (for Performance), 'test:' (for Tests), 'style:' (for Styling), 'chore:' (for Miscellaneous Tasks)"
