version: 2
mergeable:
  - when: pull_request.*
    name: "Changelog check"
    validate:
        - do: and
          validate:
            - do: dependent
              changed:
                file: 'src/**' 
                required: ['CHANGELOG.md']
            - do: dependent
              changed:
                file: 'deltachat-ffi/**'
                required: ['CHANGELOG.md']
    fail:
      - do: checks
        status: 'action_required' 
        payload:
          title: Changlog might need an update
          summary: "Changelog not updated, please check if an update is needed."
