version: 2
mergeable:
  - when: pull_request.*
    name: "Conventional Commits"
    validate:
      - do: title
        begins_with:
          match: ['feat', 'fix', 'api', 'refactor', 'perf', 'test', 'style', 'chore', 'cargo', 'build', 'ci', 'docs']

    fail:
      - do: checks
        status: "action_required"
        payload:
          title: PR title should follow conventional commits
          summary: "PR title should follow https://conventionalcommits.org. See https://github.com/deltachat/deltachat-core-rust/blob/master/CONTRIBUTING.md for details."
