[advisories]
unmaintained = "allow"
ignore = [
    "RUSTSEC-2020-0071",

    # Only affects windows if using non-default allocator (and unmaintained).
    "RUSTSEC-2021-0145",
]

[bans]
# Accept some duplicate versions, ideally we work towards this list
# becoming empty.  Adding versions forces us to revisit this at least
# when upgrading.
# Please keep this list alphabetically sorted.
skip = [
     { name = "base64", version = "<0.21" },
     { name = "block-buffer", version = "<0.10" },
     { name = "clap", version = "3.2.23" },
     { name = "clap_lex", version = "0.2.4" },
     { name = "convert_case", version = "0.4.0" },
     { name = "darling", version = "<0.14" },
     { name = "darling_core", version = "<0.14" },
     { name = "darling_macro", version = "<0.14" },
     { name = "digest", version = "<0.10" },
     { name = "env_logger", version = "<0.10" },
     { name = "getrandom", version = "<0.2" },
     { name = "hermit-abi", version = "<0.3" },
     { name = "humantime", version = "<2.1" },
     { name = "idna", version = "<0.3" },
     { name = "nom", version = "<7.1" },
     { name = "portable-atomic", version = "<1.0" },
     { name = "quick-error", version = "<2.0" },
     { name = "rand", version = "<0.8" },
     { name = "rand_chacha", version = "<0.3" },
     { name = "rand_core", version = "<0.6" },
     { name = "sha2", version = "<0.10" },
     { name = "spin", version = "<0.9.6" },
     { name = "time", version = "<0.3" },
     { name = "version_check", version = "<0.9" },
     { name = "wasi", version = "<0.11" },
     { name = "windows-sys", version = "<0.45" },
     { name = "windows_aarch64_msvc", version = "<0.42" },
     { name = "windows_i686_gnu", version = "<0.42" },
     { name = "windows_i686_msvc", version = "<0.42" },
     { name = "windows_x86_64_gnu", version = "<0.42" },
     { name = "windows_x86_64_msvc", version = "<0.42" },
]


[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0", # Boost Software License 1.0
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-DFS-2016",
    "Zlib",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
      { path = "LICENSE", hash = 0xbd0eed23 },
]

[sources.allow-org]
# Organisations which we allow git sources from.
github = [
       "async-email",
       "deltachat",
       "n0-computer",
       "quinn-rs",
]
