# copied from http://koushiro.me/2019/04/30/Building-and-Testing-Rust-projects-on-CircleCI/

version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/deltachat-core-rust

    steps:
      - checkout

      - run:
          name: Setup build environment
          command: |
            apt update
            apt install -y curl build-essential autoconf libtool git python pkg-config libssl-dev
            # this will pick default toolchain from `rust-toolchain` file
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --default-toolchain none -y;
            source $HOME/.cargo/env
          no_output_timeout: 1800s

      - run:
          name: Format
          command: |
            export PATH=~/.cargo/bin:$PATH
            rustup component add rustfmt
            cargo fmt -- --check

      - run:
          name: Test
          command: |
            export PATH=~/.cargo/bin:$PATH
            export RUST_BACKTRACE=1
            cargo test

      - run:
          name: Build deltachat-ffi
          command: |
            export PATH=~/.cargo/bin:$PATH
            export RUST_BACKTRACE=1
            cargo build --release -p deltachat_ffi

  build_test_docs_wheel:
    machine: True
    steps:
      - checkout
      # - run: docker pull deltachat/doxygen 
      - run: docker pull deltachat/coredeps
      - run: 
          name: build docs, run tests and build wheels 
          command: ci_scripts/ci_run.sh
          environment:
            DOCS: 1
            TESTS: 1

      - run: 
           name: copying docs and wheels to workspace 
           command: |
             mkdir -p workspace/python
             # cp -av docs workspace/c-docs
             cp -av python/.docker-tox/wheelhouse workspace/
             cp -av python/doc/_build/ workspace/py-docs

      - persist_to_workspace: 
          root: workspace 
          paths: 
            # - c-docs
            - py-docs
            - wheelhouse

  upload_docs_wheels:
    machine: True
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run: ls -laR workspace 
      - run: ci_scripts/ci_upload.sh workspace/py-docs workspace/wheelhouse


workflows:
  version: 2.1
  build:
    jobs:
      - build_test_docs_wheel
      - build
      - upload_docs_wheels:
          requires:
              - build_test_docs_wheel
              - build
