[package]
name = "deltachat-repl"
version = "1.110.0"
license = "MPL-2.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1"
deltachat = { path = "..", features = ["internals"]}
dirs = "4"
log = "0.4.16"
pretty_env_logger = "0.4"
rusqlite = "0.28"
rustyline = "11"
tokio = { version = "1", features = ["fs", "rt-multi-thread", "macros"] }

[features]
default = ["vendored"]
vendored = ["deltachat/vendored"]
