name: JSON-RPC API Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add Rust cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.20.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: npm install
        run: |
          cd deltachat-jsonrpc/typescript
          npm install
      - name: Build TypeScript, run Rust tests, generate bindings
        run: |
          cd deltachat-jsonrpc/typescript
          npm run build
      - name: Run integration tests
        run: |
          cd deltachat-jsonrpc/typescript
          npm run test
        env:
          DCC_NEW_TMP_EMAIL: ${{ secrets.DCC_NEW_TMP_EMAIL }}
      - name: Run linter
        run: |
          cd deltachat-jsonrpc/typescript
          npm run prettier:check
