name: Test Nix flake

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    name: check flake formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix fmt

      # Check that formatting does not change anything.
      - run: git diff --exit-code
