name: 'node.js build'
on:
  pull_request:
  push:
    tags:
    - '*'
    - '!py-*'


jobs:
  prebuild:
    name: 'prebuild'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: System info
        run: |
          rustc -vV
          rustup -vV
          cargo -vV
          npm --version
          node --version
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.20.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.APPDATA }}/npm-cache
            ~/.npm
          key: ${{ matrix.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}-2

      - name: Install dependencies & build
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd node
          npm install --verbose

      - name: Build Prebuild
        run: |
          cd node
          npm run prebuildify
          tar -zcvf "${{ matrix.os }}.tar.gz" -C prebuilds .

      - name: Upload Prebuild
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: node/${{ matrix.os }}.tar.gz

  pack-module:
    needs: prebuild
    name: 'Package deltachat-node and upload to download.delta.chat'
    runs-on: ubuntu-18.04
    steps:
      - name: install tree
        run: sudo apt install tree
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        continue-on-error: true
      - name: Get Pullrequest ID
        id: prepare
        run: |
          tag=${{ steps.tag.outputs.tag }}
          if [ -z "$tag" ]; then
            node -e "console.log('DELTACHAT_NODE_TAR_GZ=deltachat-node-' + '${{ github.ref }}'.split('/')[2] + '.tar.gz')" >> $GITHUB_ENV
          else
            echo "DELTACHAT_NODE_TAR_GZ=deltachat-node-${{ steps.tag.outputs.tag }}.tar.gz" >> $GITHUB_ENV
            echo "No preview will be uploaded this time, but the $tag release"
          fi
      - name: System info
        run: |
          rustc -vV
          rustup -vV
          cargo -vV
          npm --version
          node --version
          echo $DELTACHAT_NODE_TAR_GZ
      - name: Download ubuntu prebuild
        uses: actions/download-artifact@v1
        with:
          name: ubuntu-18.04
      - name: Download macos prebuild
        uses: actions/download-artifact@v1
        with:
          name: macos-latest
      - name: Download windows prebuild
        uses: actions/download-artifact@v1
        with:
          name: windows-latest
      - shell: bash
        run: |
          mkdir node/prebuilds
          tar -xvzf ubuntu-18.04/ubuntu-18.04.tar.gz -C node/prebuilds
          tar -xvzf macos-latest/macos-latest.tar.gz -C node/prebuilds
          tar -xvzf windows-latest/windows-latest.tar.gz -C node/prebuilds
          tree node/prebuilds
          rm -rf ubuntu-18.04 macos-latest windows-latest
      - name: install dependencies without running scripts
        run: |
          npm install --ignore-scripts
      - name: build constants
        run: |
          npm run build:core:constants
      - name: build typescript part
        run: |
          npm run build:bindings:ts
      - name: package
        shell: bash
        run: |
          mv node/README.md README.md
          npm pack .
          ls -lah
          mv $(find deltachat-node-*) $DELTACHAT_NODE_TAR_GZ
      - name: Upload Prebuild
        uses: actions/upload-artifact@v1
        with:
          name: deltachat-node.tgz
          path: ${{ env.DELTACHAT_NODE_TAR_GZ }}
      # Upload to download.delta.chat/node/preview/
      - name: Upload deltachat-node preview to download.delta.chat/node/preview/
        if: ${{ ! steps.tag.outputs.tag }}
        id: upload-preview
        shell: bash
        run: |
          echo -e "${{ secrets.SSH_KEY }}" >__TEMP_INPUT_KEY_FILE
          chmod 600 __TEMP_INPUT_KEY_FILE
          scp -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE -P "22" -r $DELTACHAT_NODE_TAR_GZ "${{ secrets.USERNAME }}"@"download.delta.chat":"/var/www/html/download/node/preview/"
        continue-on-error: true
      - name: "Post links to details"
        if: steps.upload-preview.outcome == 'success'
        run: node ./node/scripts/postLinksToDetails.js
        env:
         URL: preview/${{ env.DELTACHAT_NODE_TAR_GZ }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Upload to download.delta.chat/node/
      - name: Upload deltachat-node build to download.delta.chat/node/
        if: ${{ steps.tag.outputs.tag }}
        id: upload
        shell: bash
        run: |
          echo -e "${{ secrets.SSH_KEY }}" >__TEMP_INPUT_KEY_FILE
          chmod 600 __TEMP_INPUT_KEY_FILE
          scp -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE -P "22" -r $DELTACHAT_NODE_TAR_GZ "${{ secrets.USERNAME }}"@"download.delta.chat":"/var/www/html/download/node/"
