name: Remote tests
on: [push]
jobs:
  remote_tests_python:
    name: Remote Python tests
    runs-on: ubuntu-latest
    env:
      DCC_NEW_TMP_EMAIL: ${{ secrets.DCC_NEW_TMP_EMAIL }}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -m 700 -p ~/.ssh
      - run: touch ~/.ssh/id_ed25519
      - run: chmod 600 ~/.ssh/id_ed25519
      - run: 'echo "$SSH_KEY" | base64 -d > ~/.ssh/id_ed25519'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: scripts/remote_tests_python.sh "deltachat-core/python/${{ github.ref }}/${{ github.run_number }}"
